spring.application.name=backoffice

spring.datasource.url=jdbc:postgresql://localhost:5432/anglican_db_mg
spring.datasource.username=postgres
spring.datasource.password=4185
spring.jpa.hibernate.ddl-auto=update

jwt.secret=SzUjbVEhMnhGdjgqclo0JHdMMV9uTjdAYkM1JmpSMyV0RzYoeVg5KQ==
jwt.expiration=86400000

port=8080