spring.application.name=backoffice

spring.datasource.url=jdbc:postgresql://localhost:5432/anglican_db_mg
spring.datasource.username=postgres
spring.datasource.password=4185
spring.jpa.hibernate.ddl-auto=update

port=8080